### ISSUE TITLE
Gaya Penulisan Kode dan Mengubah Fungsi Menjadi Properti Penghitung

### ISSUE THREAD

**Issue by jefrydco** [lutzid/Subtitle_Finder#1]
Hi Mas Zidan, terima kasih telah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Zidan.

Mas juga sudah menggunakan kerangka CSS Bootstrap, luar biasa Mas!

Namun saya ada 2 saran kecil Mas untuk kode yg Mas kirim

1. Gaya Penulisan Kode
Pada berkas `index.html` baris ke 67-68:

https://github.com/lutzid/Subtitle_Finder/blob/1462dc080597007c0dc7d966aed087e2ed88bd24/index.html#L67-L68

Menurut saya akan lebih baik jika Mas menambahkan spasi antara `{{` dan `}}` sehingga kurang lebih kode tersebut menjadi `{{ secondsConverter(result.start) }}`

2. Mengubah Fungsi Menjadi Properti Penghitung
Menurut saya fungsi `secondsConverter` itu akan lebih baik jika diubah menjadi properti penghitung Mas. Karena hasil kalkulasi dari properti penghitung akan di _cache_.

Karena kita perlu menerima parameter untuk menampilkan hasilnya, kita bisa mengembalikan nilai berupa fungsi Mas. Kurang lebih kode fungsi tersebut jika diubah menjadi properti penghitung akan menjadi seperti berikut:

```javascript
computed: {
  secondsConverter() {
    return (timestamp) => {
      // Kode di dalamnya
      return hours + ':' + minutes + ':' + seconds 
    }
  }
}
```

Lebih lanjut mengenai perbedaan fungsi dan properti penghitung dapat Mas baca pada tautan berikut, [Dokumentasi Vue.js Bahasa Indonesia - Properti Penghitung vs Metode](https://docs.vuejs.id/v2/guide/computed.html#Penyimpanan-Penghitung-Computed-Cache-vs-Metode).

Semangat Mas! 😄

**Comment by lutzid** [comment]
Baik Mas. Sudah saya perbaiki sesuai dengan saran Mas Jefry.  Terimakasih atas masukannya
